### ISSUE TITLE
Milestone 1 Comments:

### ISSUE THREAD

**Issue by Glenn032787** [UBC-MDS/boardgame_rating_predictor#14]
Congratulations on finishing milestone 1! We can see you put a lot of work into this project, nice work! Below we list some specific feedback you can use to improve your project.

We provide tick boxes for you to use in the future as you address these concerns to improve the final grade of your project. If anything is unclear, please feel free to ask questions in this issue thread.

***1. Project set-up (max 20 points)***
- [ ] Contributing documentation should reflect all the ways people can contribute to the project 
(core members, who should be working in a GitHub flow workflow involving branching in the main project repo and opening PR's, as well as arms-length contributors, who more likely may have to fork the repo before submitting a PR). **-2**
**Comment:**  Core teams contribution workflow is not mentioned.

***2. Project proposal (10 points)***
Good Job!

***3. A script that downloads and saves the data***
Great Job!

***4. Exploratory data analysis in a literate code document***
- [x] There figure captions for the tables should be above the table. **-1** **viz**
**Comment:** All figures should have captions below and tables should have captions above. See here for [example](https://clauswilke.com/dataviz/visualizing-amounts.html#tab:boxoffice-gross)
- [x] There is not title, introduction and/or references in the analysis (`.ipynb` or `.Rmd`) file **-2**
**Comment:** Would be good to add introduction in EDA document to explain purpose or goal of the script.
- [x] Narration of methods and method choices was not as clear and thorough as expected. -1
**Comment:** You should discuss how you would deal with the the list items (i.e some games have boardgamemechanic as ['Card Drafting', 'Hand Management'] and some games have ['Card Drafting']). Would does be two completely separate encoding? Also would be great to include color sepperate high/low rating in Distribution of Numeric Features figures.

***Expectations***
- [ ] Please provide the link to the release as https://github.com/UBC-MDS/REPOSITORY/tree/VERSION

**Comment by erictsai1208** [comment]
Just wanted a clarification on figure captions. Are figure captions necessary even for the figures that are unimportant and will not be used later on? For example, I used `df.info()` to see which columns I want to drop, but that is just scratch work and ultimately is unimportant in the analysis. Because other than that, I believe we have all necessary figure captions.

**Comment by Glenn032787** [comment]
It is best practice to include figure captions for all figures and tables. As this is suppose to be a report, if you don't think that the table/figures are important than you shouldn't include it, but if you do decide to show it, you should include a description. It is great that you included titles for the tables, but would be good to include a one line description for the caption.
